name: Deploy Frontend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "public/**"
      - "package*.json"
      - "vite.config.*"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add EC2 host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -T 10 -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: SSH deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # if you use a custom port: port: ${{ secrets.SSH_PORT }}
          script: |
            set -euo pipefail
            FRONTEND_DIR=/srv/app/frontend/law_firm_frontend

            echo "[pull] $FRONTEND_DIR"
            cd "$FRONTEND_DIR"
            git fetch --all
            git reset --hard origin/main

            echo "[env]"
            [ -f .env ] || echo "VITE_API_BASE=/api" > .env

            echo "[build]"
            npm ci || npm install
            npm run build

            echo "[restart]"
            sudo systemctl restart law-firm-frontend
            sudo systemctl status law-firm-frontend --no-pager -l | tail -n 30
